# gem "github-pages", group: :jekyll_plugins
# gem "jekyll-remote-theme"

source "https://rubygems.org"

gem "jekyll"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-seo-tag"

gem "github-pages", group: :jekyll_plugins